---
:#: "id"
:Name: "name"
:Type 1: "type_1"
:Type 2: "type_2"
:Total: "total"
:HP: "hp"
:Attack: "attack"
:Defense: "defense"
:Sp. Atk: "sp_atk"
:Sp. Def: "sp_def"
:Speed: "speed"
:Generation: "generation"
:Legendary: "legendary"
